### ISSUE TITLE
Undefined handle_info

### ISSUE THREAD

**Issue by ZombieHarvester** [larskrantz/logger_papertrail_backend#14]
Hi there, i've upgraded to 1.0 and getting this in my logs

`** Undefined handle_info in LoggerPapertrailBackend.Logger ** Unhandled message: {:io_reply, #Reference<0.4016286325.3924295681.75944>, :ok} `

elixir 1.5.2
phoenix 1.3

**Comment by larskrantz** [comment]
Thanks for your report. 
Very strange, have no idea where it comes from. Found this http://erlang.org/doc/apps/stdlib/io_protocol.html and will investigate further.

**Comment by ZombieHarvester** [comment]
yeah, it generated a gig of logs within minutes, which hit the limit on papertrail. I had to downgrade to the previous version

**Comment by larskrantz** [comment]
Turns out when using `@behaviour :gen_event` one actually need to behave, so when looking at the old GenEvent we needed to add unhandled messages, events, code-change and terminate.
ping @nallwhy
