### ISSUE TITLE
Warnings don't get mapped to the right syslog level

### ISSUE THREAD

**Issue by dmt** [larskrantz/logger_papertrail_backend#15]
I was trying to find our warnings in papertrail querying for "severity:warning" and couldn't find any though they do get logged as "severity:info". 

I have the suspicion that this is because of 
https://github.com/larskrantz/logger_papertrail_backend/blob/master/lib/logger_papertrail_backend/message_builder.ex#L62-L66 where `:warn` instead of `:warning` would fall through to the default.

**Comment by larskrantz** [comment]
Good catch - I'm on it.
Thanks!

**Comment by larskrantz** [comment]
Please use version 1.0.2 from [hex.pm](https://hex.pm/packages/logger_papertrail_backend).

**Comment by dmt** [comment]
Thanks!
