### ISSUE TITLE
Log level mismatch in config does not send logs to papertrail

### ISSUE THREAD

**Issue by fjahr** [larskrantz/logger_papertrail_backend#17]
I followed the readme and simply copy+pasted the configs. Unfortunately, I did not receive any logs in Papertrail and also did not see any errors. I then found that this seems to be caused by the different log levels in the config examples of the readme. `:warn` on the `:logger_papertrail_backend` does not work in combination with `:debug` in the `:logger` config. When I changed it to `:debug` for both it started to work.

I am working on a Phoenix 1.3 App with Elixir 1.5.

I have created a new app that reproduces the error: https://github.com/fjahr/papertrail_test/blob/master/config/dev.exs#L62

I am not clear yet on what the real cause of the issue is and if it can be fixed here but I think at least there should be a hint in the readme because it can be confusing since there are no errors. I am not clear yet how the interaction between the different log levels really works because I did not find general documentation on that. Otherwise, I would have created a PR :)

**Comment by larskrantz** [comment]
Sorry, but after almost a year and lot's of production logging, and testing your example app, I still have not been able to reproduce. Closing for now.

**Comment by shritesh** [comment]
Thanks @fjahr. I too followed the Readme and encountered the same issue. Both `:logger_papertrail_backend` and  `:logger`'s level have to be the same, otherwise logs don't show up.
