### ISSUE TITLE
:inet.getaddr MatchError

### ISSUE THREAD

**Issue by Mazyod** [larskrantz/logger_papertrail_backend#4]
Hello,

Apologies for the lack of details, but I just happen to find this error in my papertrail logs, so thought I'd document it here..

```
00:59:08.923 [error] GenServer LoggerPapertrailBackend.Sender terminating 
** (MatchError) no match of right hand side value: {:error, :nxdomain}
     (logger_papertrail_backend) lib/logger_papertrail_backend/sender.ex:47: LoggerPapertrailBackend.Sender.resolve_host/1
     (logger_papertrail_backend) lib/logger_papertrail_backend/sender.ex:51: LoggerPapertrailBackend.Sender.resolve_add_host/2
     (logger_papertrail_backend) lib/logger_papertrail_backend/sender.ex:16: LoggerPapertrailBackend.Sender.handle_cast/2
     (stdlib) gen_server.erl:601: :gen_server.try_dispatch/4
     (stdlib) gen_server.erl:667: :gen_server.handle_msg/5
     (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
```

**Comment by Mazyod** [comment]
I just realize it could be my mistake (probably is) for passing in wrong parameters .. Sorry about that, wish I could delete this. I'll investigate more.

**Comment by larskrantz** [comment]
Thanks for using it, keep 'em coming if you experience something strange!

**Comment by Mazyod** [comment]
ok, so I'm now getting spammed with this error on two DigitalOcean servers I have with papertrail loggers. One is running a phoenix app, and the other is running a plain elixir app with a websocket client.

I've tried to research the issue, but all I could find is that `:inet.getaddr` might return an error tuple, and that case is not handled in `sender.ex` in this repo:
http://erlang.org/doc/man/inet.html#getaddr-2

This is the most common stacktrace I have:

```
Oct 21 04:14:28 DamaBots DamaBots:   [error] GenServer LoggerPapertrailBackend.Sender terminating 
** (MatchError) no match of right hand side value: {:error, :nxdomain}
     (logger_papertrail_backend) lib/logger_papertrail_backend/sender.ex:47: LoggerPapertrailBackend.Sender.resolve_host/1
     (logger_papertrail_backend) lib/logger_papertrail_backend/sender.ex:36: LoggerPapertrailBackend.Sender.refresh_ip/2
     (stdlib) lists.erl:1263: :lists.foldl/3
     (logger_papertrail_backend) lib/logger_papertrail_backend/sender.ex:25: LoggerPapertrailBackend.Sender.handle_info/2
     (stdlib) gen_server.erl:601: :gen_server.try_dispatch/4
     (stdlib) gen_server.erl:667: :gen_server.handle_msg/5
     (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
```

**EDIT**:
OS: Ubuntu 14.04.5
Erlang: 19
Elixir: 1.3.2

**Comment by larskrantz** [comment]
Thanks, I'll look into it. 
Should be an easy fix - it refreshes the ip in intervals, and if it gets the `{:error, _}`-tuple, it should just keep the latest resolved ip.

**Comment by larskrantz** [comment]
@Mazyod - if you could test with master, I would appreciate it!

**Comment by Mazyod** [comment]
Thanks! Interestingly, I'm not getting this problem anymore (like before), since I am guessing the lookup is succeeding for now. Might've been a glitch in DigitalOcean... If I ever get it again, I'll update and test.
